import platform
from .loader import get_config_value
LAUNCHER_VERSION = '2.1.3stable'
APP_ID = 'deltahub.y.114'
DATA_FIREBASE_URL = get_config_value('DATA_FIREBASE_URL', '')
CLOUD_FUNCTIONS_BASE_URL = get_config_value('CLOUD_FUNCTIONS_BASE_URL', '')
STEAM_APP_ID_FULL, STEAM_APP_ID_DEMO, STEAM_APP_ID_UNDERTALE = ('1671210', '1690940', '391540')
GAME_PROCESS_NAMES = ['DELTARUNE.exe', 'DELTARUNE', 'UNDERTALE.exe', 'UNDERTALE', 'Undertale Yellow.exe', 'Undertale Yellow', 'runner']
SAVE_SLOT_FINISH_MAP = {0: 3, 1: 4, 2: 5}
ARCH = platform.machine()
SOCIAL_LINKS = {'telegram': 'https://t.me/y_maintg', 'discord': 'https://discord.gg/gg4EvZpWKd'}
UI_COLORS = {'status_error': 'red', 'status_warning': 'orange', 'status_success': 'green', 'status_info': 'gray', 'status_ready': 'lightgreen', 'status_steam': 'blue', 'link': '#00BFFF', 'social_discord': '#8A2BE2', 'saves_button': 'yellow'}
THEMES = {'default': {'name': 'Deltarune', 'background': 'images/bg_fountain.gif', 'font_family': 'Determination Sans Rus', 'font_size_main': 16, 'font_size_small': 12, 'colors': {'main_fg': '#000000', 'top_level_fg': '#000000', 'button': '#000000', 'button_hover': '#333333', 'button_text': '#FFFFFF', 'border': '#FFFFFF', 'text': '#FFFFFF'}}}
BROWSER_HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
NETWORK_TIMEOUT_SHORT = 5
NETWORK_TIMEOUT_MEDIUM = 15
NETWORK_TIMEOUT_LONG = 60
NETWORK_TIMEOUT_HEAD = 15
SPLASH_MIN_DURATION = 10.0
INITIALIZATION_TIMEOUT = 5000
ONLINE_UPDATE_INTERVAL = 30000
LAUNCHER_FALLBACK_TIMEOUT = 8000
SPLASH_SOUND_DELAY = 1000
LEGACY_CLEANUP_DELAY = 1000
SPLASH_RETRY_DELAY = 100
IMAGE_CACHE_MAX_SIZE = 100
NETWORK_SEMAPHORE_LIMIT = 4
THREAD_WAIT_TIMEOUT = 2000
GAME_MONITOR_WAIT = 1000
STATUS_UPDATE_DELAY = 100
UI_REFRESH_DELAY_1 = 100
UI_REFRESH_DELAY_2 = 200
UI_REFRESH_DELAY_3 = 300
DOWNLOAD_CHUNK_SIZE = 262144
MAX_DOWNLOAD_RETRIES = 5
SLOT_ID_UNIVERSAL = -1
SLOT_ID_DEMO = -10
SLOT_ID_UNDERTALE = -20
SLOT_ID_UNDERTALE_YELLOW = -30
SLOT_ID_MENU = 0
SLOT_ID_CHAPTER_1 = 1
SLOT_ID_CHAPTER_2 = 2
SLOT_ID_CHAPTER_3 = 3
SLOT_ID_CHAPTER_4 = 4
DATA_FILE_EXTENSIONS = ('.xdelta', '.vcdiff', '.csx', '.win')
GAMEBANANA_API_BASE = 'https://gamebanana.com/apiv11'
GAMEBANANA_GAME_IDS = {'deltarune': 6755, 'undertale': 5506, 'undertaleyellow': 19606}
GAMEBANANA_UPDATE_CHECK_INTERVAL = 3600
GAMEBANANA_PER_PAGE = 20
GAMEBANANA_MAX_PAGES = 50
