"""Configuration constants for the mod patching system."""

from config import constants as _constants

EXPORT_SCRIPT_CONFIGS = _constants.EXPORT_SCRIPT_CONFIGS
IMPORT_SCRIPT_CONFIGS = _constants.IMPORT_SCRIPT_CONFIGS
SCRIPT_TYPES = _constants.SCRIPT_TYPES
ASSET_TRACKING_CONFIGS = _constants.ASSET_TRACKING_CONFIGS
PATCH_SUBDIRS = _constants.PATCH_SUBDIRS
XDELTA_ERROR_MAP = _constants.XDELTA_ERROR_MAP
XDELTA_EXCEPTION_ERROR_KEYS = _constants.XDELTA_EXCEPTION_ERROR_KEYS
COMPILATION_ERROR_PATTERNS = _constants.COMPILATION_ERROR_PATTERNS
SKIP_FILES = _constants.SKIP_FILES
ARCHIVE_EXTENSIONS = _constants.ARCHIVE_EXTENSIONS

__all__ = [
    'EXPORT_SCRIPT_CONFIGS',
    'IMPORT_SCRIPT_CONFIGS',
    'SCRIPT_TYPES',
    'ASSET_TRACKING_CONFIGS',
    'PATCH_SUBDIRS',
    'XDELTA_ERROR_MAP',
    'XDELTA_EXCEPTION_ERROR_KEYS',
    'COMPILATION_ERROR_PATTERNS',
    'SKIP_FILES',
    'ARCHIVE_EXTENSIONS',
]
